---
# Source: stockticker/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stockticker
  namespace: stockticker
  labels:
    app.kubernetes.io/name: stockticker
    helm.sh/chart: stockticker-0.1.0
    app.kubernetes.io/instance: stockticker
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  APIKEY: "a2V5"
