---
# Source: stockticker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockticker
  namespace: stockticker
  labels:
    app.kubernetes.io/name: stockticker
    helm.sh/chart: stockticker-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: stockticker
automountServiceAccountToken: false
