{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stockticker.fullname" . }}
  namespace: {{ include "stockticker.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "stockticker.name" . }}
    helm.sh/chart: {{ include "stockticker.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "stockticker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
