{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stockticker.fullname" . }}
  namespace: {{ include "stockticker.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ template "stockticker.name" . }}
    helm.sh/chart: {{ template "stockticker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
