alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  podDisruptionBudget:
    enabled: false
  persistentVolume:
    enabled: false
  global:
    scrape_interval: 15s
    scrape_timeout: 2s
    evaluation_interval: 15s
