architecture: standalone

auth:
  enabled: false

master:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi
  persistence:
    enabled: false
  pdb:
    create: false
